In [21]:
import pandas as pd

In [39]:
preco = pd.read_csv('preco.csv')

In [42]:
quantidade = pd.read_csv('quantidade.csv')

In [41]:
preco.head()

,Data,Preço médio - gás GLP - tonelada - R$ - Agência Nacional do Petróleo (ANP) - ANP_PRGLP,Unnamed: 2
0,1973,1240.0,NaN
1,1974,1960.0,NaN
2,1975,2640.0,NaN
3,1976,3440.0,NaN
4,1977,4940.0,NaN

In [43]:
quantidade.head()

,Data,Consumo aparente - gás GLP - média - quantidade/dia - Barril - Agência Nacional do Petróleo (ANP) - ANP12_CGLP12,Unnamed: 2
0,1979,80.0,NaN
1,1980,85.0,NaN
2,1981,91.0,NaN
3,1982,102.0,NaN
4,1983,106.0,NaN

In [17]:
preco_inicial = float(input("Digite o valor: \n"))
preco = float(input("Digite o valor: \n"))
quantidade_inicial = float(input("Digite o valor: \n"))
quantidade = float(input("Digite o valor: \n"))

Digite o valor:
 2
Digite o valor:
 1
Digite o valor:
 3
Digite o valor:
 4

In [18]:
import math

In [36]:
if quantidade_inicial != 0 and preco_inicial != 0 and quantidade/quantidade_inicial != 0 and preco/preco_inicial !=0 and preco/preco_inicial != 1:
    e = (math.log(quantidade/quantidade_inicial))/(math.log(preco/preco_inicial))
    print(f"\nO valor da elasticidade-preço da demanda é igual a {e}.\n")
else:
    print("Erro! Valores inválidos ou preço inalterado")

O valor da elasticidade-preço da demanda é igual a -0.4150374992788437.